version: "{build}"

clone_depth: 1

install:
  - cinst wget
  - cmd: wget http://curl.haxx.se/ca/cacert.pem -O C:\cacert.pem
  - SET SSL_CERT_FILE=C:\cacert.pem
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet
  - bundler --version
  - bundle install

build: off

test_script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter

environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"
